version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: Echo the env
          command: echo "This is inside the cmd"
      - run:
          name: Create a text file and Zip it
          command: |
            mkdir \app ; cd \app ;
            runas echo.>test.txt; Compress-Archive test.txt ${CIRCLE_BUILD_NUM}-output.zip
      - store_artifacts:
          path: .\app\${CIRCLE_BUILD_NUM}\${CIRCLE_BUILD_NUM}-output.zip
