version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: Echo the env
          command: echo "This is inside the cmd"
      - run:
          name: Try "Hello World!!" app
          command: dotnet new console -o myApp; cd myApp; dotnet run; dotnet publish -c Release -o out
      - store_artifacts:
          path: .\app\${CIRCLE_BUILD_NUM}\${CIRCLE_BUILD_NUM}-output.zip
